Amazon/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Amazon.Models;
namespace Amazon.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public CartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Amazon/Components/TypesViewComponent.cs
using Amazon.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Amazon.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }

        public TypesViewComponent(IBookStoreRepository temp) => repo = temp;

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Amazon/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <span class="badge bg-info" style="float:right">
            Price: @Model.Price
        </span>
    </div>


    <ul>
        <li>Category: @Model.Category</li>
        <li>Author: @Model.Author</li>
        <li>Isbn: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>

        <li>Publisher: @Model.Publisher</li>
        <li>Number of Pages: @Model.PageCount</li>
    </ul>

    <form method="post" asp-page="/AddBook">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>

    </form>

</div>

Amazon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="navbar-brand m-lg-2">Amazon</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    @* I added a bootstrap style that makes a banner across the screen that follows the top of the screen when you scroll down I also used an outline of danger*@
    <div class="row bg-info gx-xxl-1 sticky-md-top alert text-md-center text-dark text-warning text-white border-danger alert-danger">
        <p class="fa-thumbs-up align-content-center">Welcome to my Amazon website from the early 2000's</p>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>


        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
        <footer style="padding-top:50px; text-align:center;">Copyright Amazon 2022</footer>
    </div>


</body>
</html>